### ISSUE TITLE
[Bug] Unable to load laravel socket.io leads to Chatbox not displaying new messages unless page refresh

### ISSUE THREAD

**Issue by k-304** [sysu-ipv6/UNIT3D-Community-Edition#44]
I'm running the latest version of your docker container (syspt 4days old, laravel-echo-server 7 weeks old) and the newset code.
When I open the dev. tools in my browser I see the following error message repeated every couple seconds.:
`GET https://192.168.1.10:8443/socket.io/?EIO=3&transport=polling&t=N4O8s3k net::ERR_CONNECTION_TIMED_OUT`

Running a CURL from the app container to `https://192.168.1.10:8443/socket.io/?EIO=3&transport=polling&t=N4O8s3k` i get back:
`[2]+  Done                       curl 
[1]+  Done(35)                   curl https://192.168.1.10:8443/socket.io/?EIO=3`

Reason why I would like to solve this issue is that within the chatbox, the autorefresh does not work.

Thanks in advice for any help.

**Comment by howardlau1999** [comment]
I don't know how you are running your containers. The socket.io functionality is dependent only on the `laravel-echo-server` container. Given that your connection did not get refused, I guess you are probably missing a configuration file called `laravel-echo-server.json`. You can refer to https://github.com/sysu-ipv6/UNIT3D-Deploy to get a template and modify it on demand. The file is quite self-explanatory. Just point the `authHost` to your UNIT3D app url.

For the container to work, you need to mount that json file into container's `/app/laravel-echo-server.json` and configure at least one client key. You can add a client key by running command `docker run -it -v /path/on/your/host/to/json:/app/laravel-echo-server.json -- laravel-echo-server client:add`

If the json file file finds its way into container but you still have trouble connecting socket.io, you probably forget to map the host port to the container port.

**Comment by k-304** [comment]
Thanks for your reply. Really appreciate it.

There was indeed a problem with the "authhost", i did not changed it to nginx since you have moved web/app apart. I changed this:
`"authHost": "http://nginx",`
then run docker-compose down & up to load the new file into the container, a complete "run init" is not necessary after this change, is it?
Nginx is resolveable within the docker setup.
But I still got the same error in my browser console... 

Some more details to my setup:
I run the latest containers with docker-compose. I run them like in your description.
Theres the nginx, app, laravel, redis and queue Container. Only difference, I run MySQL on a physical host.
In "front" of the nginx proxy there is another proxy running on my physical machine, redirecting all traffic to nginx:8090. I know this is not the best setup, but hadn't time to adopt the nginx config to apache2 yet.

Also the laravel server is listening on port 8433 mapped to 6001 (tcp).
Docker PS:
`sysuipv6/syspt:latest                 "docker-php-entrypoi…"   3 minutes ago       Up 3 minutes                                  unit3d_queue_worker_1
nginx:alpine                          "nginx -g 'daemon of…"   3 minutes ago       Up 3 minutes        0.0.0.0:8090->80/tcp      unit3d_nginx_1
sysuipv6/syspt:latest                 "docker-php-entrypoi…"   3 minutes ago       Up 3 minutes                                  unit3d_app_1
sysuipv6/laravel-echo-server:latest   "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes        0.0.0.0:8443->6001/tcp    unit3d_laravel_echo_server_1
redis:5                               "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes        6379/tcp                  unit3d_redis_1`

Btw. could this explain some chat issues?

**Comment by howardlau1999** [comment]
Maybe the problem is that the echo server serves HTTP service but you are trying to connect it using HTTPS. You can try adding certificate paths in the json file. Frankly, I also put another nginx in "front" of the whole docker containers which serves SSL service.

**Comment by howardlau1999** [comment]
I don't know if this is related to any chat issues. But I think it should only affect real-time notifications of chat room or something like that.

**Comment by howardlau1999** [comment]
You can `docker logs -f $CONTAINER_ID` to check whether the echo server has successfully started up.

**Comment by howardlau1999** [comment]
I am running the containers with `"authHost": "http://nginx"` too and everything works fine. Your curl command is missing quotation marks with URL. The correct way to curl is `curl -v "http://YOUR_IP:8443/socket.io/?EIO=3&transport=polling&t=N4O8s3k"` otherwise the `&` in the URL will be interpreted as a background task operator.

**Comment by howardlau1999** [comment]
Since you have run the `init` process, there is no need to re-run it.

**Comment by k-304** [comment]
Thanks for your reply!

I was able to get laravel echo server running with https enabled and certs added. 
A curl to the internal ip and port was successful.
But since I think that the traffic was routed through WAN I opened up firewall ports, but this does not work although the service is available through WAN (canyouseeme.org check to port 8443 was OK).
Is there a way to prevent the app to take the domain and use an IP instead? I changed the file `/app/resources/js/bootstrap.js` which was the only one related to "socketio" (see: https://github.com/HDInnovations/UNIT3D-Community-Edition/search?q=8443&unscoped_q=8443)  from `window.location.hostname + ':8443',` to `host: 'internal_ip:8443',` but the app is still trying to connect to the domain.com:8443/socketio.

**Comment by k-304** [comment]
let me be more specific about the issue I hope to solve:
Wen sending or receiving a chat message, the chat does not refresh itself. I need to run a full page refresh every time i send a message until it appears within the chatbox.

**Comment by k-304** [comment]
> I am running the containers with `"authHost": "http://nginx"` too and everything works fine. 

Does your app also connect to domain.com and is routed over WAN or is it somehow only internal?

**Comment by howardlau1999** [comment]
My app is running on a hostname open to the Internet and everything works fine. The port to connect to socket.io API endpoint is hardcoded but the address is based on your browser location. That means if you visit your app with internal ip then it will use the internal ip to connect socket.io.

This seems more like a networking problem on your host. I have no idea why you still get connection timed out. If you want to change the way it connects to the socket.io, you need to fork the repository (either mine or HDInnovations) and search and replace the hardcoded 8443.

Another way I can come up with is use your "front" reverse proxy to proxy the websokcet connections to your laravel echo server container.


获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by k-304** [comment]
I was able to resolve the SocketIo issue, configureing my proxy to as well forward port 8443 traffic.
Thanks for your help.

The chat issue I hoped to solve still exists, it that the chat does not show the message after you hit "enter" and send it. you need to refresh the page by hand... should i open a new issue for that?

**Comment by k-304** [comment]
I can confirm that the laravel socketIO issue has solved the not updating chat.
Now every time a message is sent, it will be shown in the chatbox instantly.

**Comment by k-304** [comment]
Title Updated & Closed.
