### ISSUE TITLE
Updating to newer Releases

### ISSUE THREAD

**Issue by k-304** [sysu-ipv6/UNIT3D-Community-Edition#47]
Hi, 

Do you have any recommendations for updating to a newer version?
In this case from 2.2.7 to 2.8.

When pulling the latest image and run ```docker-compose -f docker-compose.init.yml run init```  again there are some errors when Seeding the DB tables, for example due to tables exist and have foreign keys:
```
In Connection.php line 669:

  t fails (`torrent_tracker_unit3d_test`.`achievement_progress`, CONSTRAINT `achievement_progress_achievement_id_fore
  ign` FOREIGN KEY (`achievement_id`) REFERENCES `achievement_details` (`id`)) (SQL: delete from `achievement_details
  `)
```
Whats the best way to update to a newer version to get the latest data and have the DB tables seeded/updated as well?

Thanks in advice!

**Comment by howardlau1999** [comment]
I updated by commenting out seeder classes that caused this error. I think the seeders are not designed idempotent which means you cannot execute them more than once. Maybe you could try removing the foreign key constraints in your database and try seeding again?

**Comment by k-304** [comment]
Thanks, gonna try it this way.
Have you looked into the update script which unit3d provides for "standard" installations? Maybe a modified version of it could also make the docker update process easier...

**Comment by howardlau1999** [comment]
It seems that they only provide installation script but no update script

**Comment by howardlau1999** [comment]
Maybe I will modify the seeders and submit a PR to original repo

**Comment by k-304** [comment]
i know there is a script running with php artisan to update, heres the DOCs page of it:
https://hdinnovations.github.io/UNIT3D-Docs/git_updater.html

More within this file:
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/bb0bf1e97f88881461e5ad9cbad8c227e797feb7/app/Console/Commands/GitUpdater.php

**Comment by howardlau1999** [comment]
Seems that they only run migrations not seedings

**Comment by k-304** [comment]
Means that we could skip this line (https://github.com/sysu-ipv6/UNIT3D-Deploy/blob/5f7a4f796638b20d72efeb08e69dd4bc102d68b3/docker-compose.init.yml#L23) and add something to just migrate it?
Eg:
``` su www-data -s /bin/sh -c "php artisan migrate"```

**Comment by howardlau1999** [comment]
If you omit the `--seed` option, you only update your database schemas. Seeding is to fill in some default data into tables. You can manually create data in tables, too.

**Comment by k-304** [comment]
assuming that when updating the important data is still there... from the 1st init.
Then when updating it would not be needed any more, as in the update script above, it is also not provided to seed the db. maybe creating a 2nd docker-compose-init.yml file for updaing? or did i got something wrong?

**Comment by howardlau1999** [comment]
Sometimes the update may need to seed a new table. In this case, you can comment out seeder classes in https://github.com/sysu-ipv6/UNIT3D-Community-Edition/blob/master/database/seeds/DatabaseSeeder.php to skip. This would be ok. Creating another .yml is no need.

**Comment by howardlau1999** [comment]
After some googling, I found that the correct way to seed single table is to run `php artisan db:seed --class=MediaLanguagesSeeder`. You can also check release notes on `https://github.com/HDInnovations/UNIT3D-Community-Edition/releases`
