### ISSUE TITLE
[Enhancement] Update to Unit3d 2.5.x

### ISSUE THREAD

**Issue by k-304** [sysu-ipv6/UNIT3D-Community-Edition#50]
Hi guys

Just wanted to ask if you noticed the new releases (2.4 & 2.5) and if you plan to update this repo soon since you are on 2.3.1 atm?

Appreciate your work and hope to get it updated soon.
Cheers!

**Comment by howardlau1999** [comment]
Thanks for your appreciation! But our team members are all quite busy at the moment, so we have to set the daily (or weekly) merging aside. Pull requests are welcome.

**Comment by howardlau1999** [comment]
Good News. We finally have some time to update it to 2.7.0. But there are too many merge conflicts during updating so the docker image may not work. Feedbacks are welcome!

**Comment by howardlau1999** [comment]
> Hi guys
> 
> Just wanted to ask if you noticed the new releases (2.4 & 2.5) and if you plan to update this repo soon since you are on 2.3.1 atm?
> 
> Appreciate your work and hope to get it updated soon.
> Cheers!

FYI, we have successfully resolved the conflicts and we are now in sync with the latest version of upstream. Besides, we have set up a robot to automatically update our fork.
